name: Hitung Kontributor

on:
  push:
    branches: [main]
  workflow_dispatch: # agar bisa dijalankan manual juga dari tab Actions

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Debug Isi File kontributor.md
        run: |
          echo "[DEBUG] Isi file kontributor.md:"
          cat kontributor.md

      - name: Hitung Jumlah Kontributor
        id: hitung
        run: |
          JUMLAH=$(grep -cE "^\s*-\s" kontributor.md)
          echo "[DEBUG] Jumlah hasil grep: $JUMLAH"
          echo "JUMLAH=$JUMLAH" >> $GITHUB_ENV

      - name: Ganti Placeholder di README
        run: |
          sed -i "s/{{jumlah_kontributor}}/${{ env.JUMLAH }}/g" README.md

      - name: Commit dan Push Perubahan
        run: |
          git add README.md
          git commit -m "🤖 update statistik kontributor (${{ env.JUMLAH }})" || echo "Tidak ada perubahan"
          git push
